[package]
name = "surf"
version = "2.0.0-alpha.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/surf"
documentation = "https://docs.rs/surf"
description = "HTTP client framework."
keywords = ["http", "client", "framework", "request"]
categories = ["web-programming", "web-programming::http-client"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>", "dignifiedquire <me@dignifiedquire.com>"]
readme = "README.md"
edition = "2018"

[features]
default = ["native-client", "middleware-logger", "encoding"]
h1-client = ["async-h1", "wasm-client"]
native-client = ["curl-client", "wasm-client", "http-client/native_client"]
hyper-client = ["hyper", "hyper-tls", "native-tls", "runtime", "runtime-raw", "runtime-tokio" ]
curl-client = ["isahc"]
wasm-client = ["js-sys", "web-sys", "wasm-bindgen", "wasm-bindgen-futures"]
middleware-logger = []
encoding = ["encoding_rs"]

[dependencies]
futures = { version = "0.3.1", features = ["compat", "io-compat"] }
http-types = "1.0.1"
log = { version = "0.4.7", features = ["kv_unstable"] }
mime = "0.3.13"
mime_guess = "2.0.3"
serde = "1.0.97"
serde_json = "1.0.40"
serde_urlencoded = "0.6.1"
url = "2.0.0"
http-client = { git = "https://github.com/dignifiedquire/http-client-1", branch = "h1", default-features = false, features = ["h1_client"] }
async-std = { version = "1.4.0", default-features = false, features = ["std"] }

# h1-client
async-h1 = { version = "1.0.0", optional = true }
pin-project-lite = "0.1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# encoding
encoding_rs = { version = "0.8.20", optional = true }

# isahc-client
isahc = { version = "0.8", optional = true, default-features = false, features = ["http2"]  }

# hyper-client
hyper = { version = "0.13.2", optional = true, default-features = false }
hyper-tls = { version = "0.3.2", optional = true }
native-tls = { version = "0.2.2", optional = true }
runtime = { version = "0.3.0-alpha.8", optional = true }
runtime-raw = { version = "0.3.0-alpha.4", optional = true }
runtime-tokio = { version = "0.3.0-alpha.6", optional = true }

# wasm-client
[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { version = "0.3.25", optional = true }
wasm-bindgen = { version = "0.2.48", optional = true }
wasm-bindgen-futures = { version = "0.4.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.25"
optional = true
features = [
    "AbortSignal",
    "Headers",
    "ObserverCallback",
    "ReferrerPolicy",
    "Request",
    "RequestCache",
    "RequestCredentials",
    "RequestInit",
    "RequestMode",
    "RequestRedirect",
    "Response",
    "TextDecoder",
    "Window",
]

[dev-dependencies]
async-std = { version = "1.0", features = ["attributes"] }
femme = "1.1.0"
serde = { version = "1.0.97", features = ["derive"] }
mockito = "0.23.3"
